import { test, expect } from '@playwright/test';
test('Navigate to myntra Home Page and search product', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter');
    await page.waitForTimeout(500)
    await expect(page).toHaveURL('https://www.myntra.com/bottle?rawQuery=bottle')
})
test('Click on the first element which opens in new tab', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    await page.waitForSelector('#\\33 2567376 > a > div.product-imageSliderContainer > div > div > div > picture > img')
    //took help from ai
    const [newPage] = await Promise.all([
    page.context().waitForEvent('page'),
    page.locator('#\\33 2567376 > a > div.product-imageSliderContainer > div > div > div > picture > img').first().click(),
])
    await newPage.waitForLoadState()
    await expect(newPage).toHaveURL('https://www.myntra.com/water-bottle/pexpo/pexpo-craft-stainless-steel-sports--hiking-single-wall-vacuum-water-bottle-950ml/32567376/buy')
})
test('Hover on the first element after search to see wishlist option', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    const locator = page.locator('#\\33 2567376 > a > div.product-imageSliderContainer > div > div > div > picture > img')
    await locator.waitFor({ state: 'visible' })
    await locator.hover()
})
test('Search a product and scroll down', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    await page.keyboard.press('PageDown')
    await page.waitForTimeout(5000)
})
test('View similar product', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    const locator = page.locator('#\\33 2567376 > a > div.product-imageSliderContainer > div > div > div > picture > img')
    await locator.waitFor({ state: 'visible' })
    await locator.hover()
    await page.locator('[id="32567376"] div').filter({ hasText: 'VIEW SIMILAR' }).click();
    await page.getByText('Similar Products').click();
    //await page.pause();
})
test('Clicking similar product', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    const locator = page.locator('#\\33 2567376 > a > div.product-imageSliderContainer > div > div > div > picture > img')
    await locator.waitFor({ state: 'visible' })
    await locator.hover()
    await page.locator('[id="32567376"] div').filter({ hasText: 'VIEW SIMILAR' }).click()
    await page.getByText('Similar Products').click();
    await page.click('#desktopSearchResults > div.search-searchProductsContainer.row-base > section > div.halfcard-leftCardContainer > div.halfcard-leftCard.halfcard-narrowLeftCard > div > div.halfcard-paddedContent > div > ul > :first-child')
})
test('Opening similar product in a new tab', async ({ page, context }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    const productImageLocator = page.locator('#\\33 2567376 > a > div.product-imageSliderContainer > div > div > div > picture > img')
    await productImageLocator.waitFor({ state: 'visible' })
    await productImageLocator.hover()
    await page.locator('[id="32567376"] div').filter({ hasText: 'VIEW SIMILAR' }).click()
    await page.getByText('Similar Products').click()
    const firstSimilarProduct = page.locator('#desktopSearchResults > div.search-searchProductsContainer.row-base > section > div.halfcard-leftCardContainer > div.halfcard-leftCard.halfcard-narrowLeftCard > div > div.halfcard-paddedContent > div > ul > :first-child')
    await firstSimilarProduct.waitFor({ state: 'visible' })
    const [newPage] = await Promise.all([
    context.waitForEvent('page'),  
    firstSimilarProduct.click()   
])
    await newPage.waitForLoadState()
    console.log('New tab title:', await newPage.title())
})
// test('Applying filter', async ({ page, context }) => {
//     await page.goto('https://www.myntra.com/')
//     await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
//     await page.keyboard.press('Enter')
//     await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
//     //await page.pause()
//     await page.click('#mountRoot > div > main > div:nth-child(3) > div.search-leftContainer.column-base > section > div > div:nth-child(2) > ul > li:nth-child(4) > label')
//     await page.waitForTimeout(500)
//     await expect(page).toHaveURL('https://www.myntra.com/bottle?f=Gender%3Aboys%20girls%2Cgirls&rawQuery=bottle')
// })
// test('clear applied filter', async ({ page, context }) => {
//     await page.goto('https://www.myntra.com/')
//     await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
//     await page.keyboard.press('Enter')
//     await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
//     //await page.pause()
//     await page.click('#mountRoot > div > main > div:nth-child(3) > div.search-leftContainer.column-base > section > div > div:nth-child(2) > ul > li:nth-child(4) > label')
//     await page.waitForTimeout(500)
//     await expect(page).toHaveURL('https://www.myntra.com/bottle?f=Gender%3Aboys%20girls%2Cgirls&rawQuery=bottle')
//     await page.click('#mountRoot > div > main > div:nth-child(3) > div.search-leftContainer.column-base > section > div > div.vertical-filters-filters.header-container > span.header-clearAllBtn')
//     await expect(page).toHaveURL('https://www.myntra.com/bottle?rawQuery=bottle')
//     await page.waitForTimeout(500)
// })
test('seeing sorting filter', async ({ page, context }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    await page.hover('.sort-sortBy')
    await page.waitForTimeout(500)
})
test('applying sorting filter', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    await page.hover('.sort-sortBy')
    await page.waitForTimeout(500)
    await page.click('text=Better Discount');
    const selectedSort = page.locator('#desktopSearchResults > div:nth-child(1) > section > div:nth-child(1) > div.horizontal-filters-sortContainer > div > div > div')
    await expect(selectedSort).toHaveText(/Better Discount/i)
    const selectedText = await selectedSort.innerText()
    console.log('Sort selected:', selectedText)
});
test('Hover on the first element and see carousel', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.fill('[placeholder="Search for products, brands and more"]', 'bottle')
    await page.keyboard.press('Enter')
    await page.waitForURL('https://www.myntra.com/bottle?rawQuery=bottle')
    const locator = page.locator('#\\33 2567376 > a > div.product-imageSliderContainer > div > div > div > picture > img')
    await locator.waitFor({ state: 'visible' })
    await locator.hover()
    await page.waitForTimeout(5000)
})
test('Home page filter', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.hover('#desktop-header-cnt > div.desktop-bound > nav > div > div:nth-child(1)')
    await page.click('text=Suits')
    await page.waitForURL('https://www.myntra.com/men-suits')
})
test('Page navigation', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.hover('#desktop-header-cnt > div.desktop-bound > nav > div > div:nth-child(1)')
    await page.click('text=Suits')
    await page.waitForURL('https://www.myntra.com/men-suits')
    await page.goBack()
    await page.waitForURL('https://www.myntra.com/')
    await page.hover('#desktop-header-cnt > div.desktop-bound > nav > div > div:nth-child(1)')
    await page.click('text=Jackets')
    await page.waitForURL('https://www.myntra.com/men-jackets')
    await page.goBack()
    await page.waitForURL('https://www.myntra.com/')
})
test('Home page scroll', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.keyboard.press('PageDown')
    await page.waitForTimeout(5000)
})
test('Profile visit', async ({ page }) => {
    await page.goto('https://www.myntra.com/')
    await page.waitForTimeout(500)
   //await page.pause() 
    await page.locator('div').filter({ hasText: /^Profile$/ }).locator('span').first().click() 
    await page.getByRole('link', { name: 'login / Signup' }).click()
})
test('LOgin and reach to otp page', async ({ page }) => {
    await page.goto('https://www.myntra.com/login/password')
    await page.fill('#mobileNumberPass','8171213263')
    // await page.pause()
    await page.locator('input[type="password"]').click()
    await page.locator('input[type="password"]').fill('3dex8v7')
    await page.getByRole('button', { name: 'LOGIN' }).click()
    await page.waitForTimeout(5000)
})
