import { test, expect  } from '@playwright/test';
test('Login with valid credentials', async ({ page }) => {
    await page.goto('https://www.saucedemo.com/')
    await page.fill('[placeholder="Username"]', 'standard_user')
    await page.fill('[placeholder="Password"]', 'secret_sauce')
    await page.click('#login-button')
    await page.waitForURL('https://www.saucedemo.com/inventory.html')
})
test.only('Login with invalid credentials', async ({ page }) => {
    await page.goto('https://www.saucedemo.com/')
    await page.fill('[placeholder="Username"]', 'standard_user1')
    await page.fill('[placeholder="Password"]', 'secret_sauce1')
    await page.click('#login-button')
    await expect(page.getByText('Username and password do not match any user in this service')).toBeVisible()
})
test('clicking on add to cart increases the count and clicking on remove button decreases the count', async ({ page }) => {
    await page.goto('https://www.saucedemo.com/')
    await page.fill('[placeholder="Username"]', 'standard_user')
    await page.fill('[placeholder="Password"]', 'secret_sauce')
    await page.click('#login-button')
    await page.waitForURL('https://www.saucedemo.com/inventory.html')
    await page.click('#add-to-cart-sauce-labs-backpack')
    await expect(page.locator('.shopping_cart_link')).toHaveText('1')
    await page.click('#remove-sauce-labs-backpack')
})
test('Clicking on shopping cart icon opens the cart and verifies oitems added in cart = items in cart',async ({page}) => {
    await page.goto('https://www.saucedemo.com/')
    await page.fill('[placeholder="Username"]', 'standard_user')
    await page.fill('[placeholder="Password"]', 'secret_sauce')
    await page.click('#login-button')
    await page.waitForURL('https://www.saucedemo.com/inventory.html')
    await page.click('#add-to-cart-sauce-labs-backpack')
    await page.click('#add-to-cart-sauce-labs-bike-light')
    await page.locator('#shopping_cart_container > a').click({ force: true })
    await page.waitForURL('https://www.saucedemo.com/cart.html')
    await expect(page.locator('.cart_item')).toHaveCount(2);
}) 
test('User can remove items from checkout tab',async ({page}) => {
    await page.goto('https://www.saucedemo.com/')
    await page.fill('[placeholder="Username"]', 'standard_user')
    await page.fill('[placeholder="Password"]', 'secret_sauce')
    await page.click('#login-button')
    await page.waitForURL('https://www.saucedemo.com/inventory.html')
    await page.click('#add-to-cart-sauce-labs-backpack')
    await page.click('#add-to-cart-sauce-labs-bike-light')
    //await page.pause()
    await page.locator('[data-test="remove-sauce-labs-backpack"]').click({ force: true })
})
